image: Visual Studio 2017
# List of preinstalled software in the image:
# https://www.appveyor.com/docs/windows-images-software/

build_script:
- set CONDA_INSTALL_LOCN=C:\\Miniconda37-x64
- call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
- call conda config --set always_yes yes --set changeps1 no
- call conda info -a
- call conda update -q conda
- call conda install -c conda-forge clang
- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd" -arch=x64
- cl /GR- /FS /FAs conv.c
- type conv.asm
- conv
- clang -S conv.c -o -
- clang -S -emit-llvm conv.c -o -

# Uncomment the following two lines to be able to login to the build worker. You
# can use the `remmina` program in Ubuntu, use the login information that the
# line below prints into the log.
#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
